"""material system versioning and sync

Revision ID: 2c9d0baa1255
Revises:
Create Date: 2026-08-19 23:46:17.879210
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "2c9d0baa1255"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "group_materials",
        sa.Column(
            "version",
            sa.Integer(),
            server_default="1",
            nullable=False,
        ),
    )
    op.add_column(
        "group_materials",
        sa.Column(
            "status",
            sa.String(length=30),
            server_default="active",
            nullable=False,
        ),
    )
    op.add_column(
        "group_materials",
        sa.Column(
            "is_active",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
        ),
    )
    op.add_column(
        "group_materials",
        sa.Column(
            "updated_by",
            sa.Integer(),
            nullable=True,
        ),
    )
    op.add_column(
        "group_materials",
        sa.Column(
            "removed_by",
            sa.Integer(),
            nullable=True,
        ),
    )
    op.add_column(
        "group_materials",
        sa.Column(
            "removed_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
    )
    op.add_column(
        "group_materials",
        sa.Column(
            "removal_reason",
            sa.Text(),
            nullable=True,
        ),
    )
    op.add_column(
        "group_materials",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )

    op.alter_column(
        "group_materials",
        "stored_name",
        existing_type=sa.String(length=255),
        type_=sa.String(length=500),
        existing_nullable=False,
    )
    op.alter_column(
        "group_materials",
        "file_path",
        existing_type=sa.String(length=500),
        type_=sa.String(length=1000),
        existing_nullable=False,
    )
    op.alter_column(
        "group_materials",
        "size",
        existing_type=sa.Integer(),
        type_=sa.BigInteger(),
        existing_nullable=False,
    )

    op.create_index(
        "ix_group_materials_version",
        "group_materials",
        ["version"],
        unique=False,
    )
    op.create_index(
        "ix_group_materials_status",
        "group_materials",
        ["status"],
        unique=False,
    )
    op.create_index(
        "ix_group_materials_is_active",
        "group_materials",
        ["is_active"],
        unique=False,
    )
    op.create_index(
        "ix_group_materials_updated_by",
        "group_materials",
        ["updated_by"],
        unique=False,
    )
    op.create_index(
        "ix_group_materials_removed_by",
        "group_materials",
        ["removed_by"],
        unique=False,
    )
    op.create_index(
        "ix_group_materials_removed_at",
        "group_materials",
        ["removed_at"],
        unique=False,
    )
    op.create_index(
        "ix_group_materials_updated_at",
        "group_materials",
        ["updated_at"],
        unique=False,
    )
    op.create_index(
        "ix_group_materials_created_at",
        "group_materials",
        ["created_at"],
        unique=False,
    )

    op.alter_column(
        "group_materials",
        "updated_at",
        server_default=None,
        existing_type=sa.DateTime(timezone=True),
        existing_nullable=False,
    )

    op.create_foreign_key(
        "fk_group_materials_updated_by_users",
        "group_materials",
        "users",
        ["updated_by"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        "fk_group_materials_removed_by_users",
        "group_materials",
        "users",
        ["removed_by"],
        ["id"],
        ondelete="SET NULL",
    )

    op.create_check_constraint(
        "chk_group_material_removed_active",
        "group_materials",
        "(status != 'removed') OR (is_active = false)",
    )
    op.create_check_constraint(
        "chk_group_material_size",
        "group_materials",
        "size > 0",
    )
    op.create_check_constraint(
        "chk_group_material_status",
        "group_materials",
        "status IN ('active', 'hidden', 'removed')",
    )
    op.create_check_constraint(
        "chk_group_material_version",
        "group_materials",
        "version >= 1",
    )

    op.add_column(
        "material_publication_requests",
        sa.Column(
            "request_type",
            sa.String(length=30),
            server_default="new_material",
            nullable=False,
        ),
    )
    op.add_column(
        "material_publication_requests",
        sa.Column(
            "target_public_material_id",
            sa.Integer(),
            nullable=True,
        ),
    )
    op.add_column(
        "material_publication_requests",
        sa.Column(
            "comparison_status",
            sa.String(length=30),
            server_default="not_required",
            nullable=False,
        ),
    )
    op.add_column(
        "material_publication_requests",
        sa.Column(
            "approved_action",
            sa.String(length=40),
            nullable=True,
        ),
    )
    op.add_column(
        "material_publication_requests",
        sa.Column(
            "approved_public_material_id",
            sa.Integer(),
            nullable=True,
        ),
    )
    op.add_column(
        "material_publication_requests",
        sa.Column(
            "proposed_title",
            sa.String(length=250),
            nullable=True,
        ),
    )
    op.add_column(
        "material_publication_requests",
        sa.Column(
            "proposed_description",
            sa.Text(),
            nullable=True,
        ),
    )

    op.create_index(
        "ix_material_publication_requests_request_type",
        "material_publication_requests",
        ["request_type"],
        unique=False,
    )
    op.create_index(
        "ix_material_publication_requests_target_public_material_id",
        "material_publication_requests",
        ["target_public_material_id"],
        unique=False,
    )
    op.create_index(
        "ix_material_publication_requests_comparison_status",
        "material_publication_requests",
        ["comparison_status"],
        unique=False,
    )
    op.create_index(
        "ix_material_publication_requests_approved_action",
        "material_publication_requests",
        ["approved_action"],
        unique=False,
    )
    op.create_index(
        "ix_material_publication_requests_approved_public_material_id",
        "material_publication_requests",
        ["approved_public_material_id"],
        unique=False,
    )
    op.create_index(
        "ix_material_publication_requests_reviewed_at",
        "material_publication_requests",
        ["reviewed_at"],
        unique=False,
    )
    op.create_index(
        "ix_material_publication_requests_updated_at",
        "material_publication_requests",
        ["updated_at"],
        unique=False,
    )

    op.alter_column(
        "material_publication_requests",
        "request_type",
        server_default=None,
        existing_type=sa.String(length=30),
        existing_nullable=False,
    )
    op.alter_column(
        "material_publication_requests",
        "comparison_status",
        server_default=None,
        existing_type=sa.String(length=30),
        existing_nullable=False,
    )

    op.create_foreign_key(
        "fk_material_publication_requests_target_public_material",
        "material_publication_requests",
        "public_materials",
        ["target_public_material_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        "fk_material_publication_requests_approved_public_material",
        "material_publication_requests",
        "public_materials",
        ["approved_public_material_id"],
        ["id"],
        ondelete="SET NULL",
    )

    op.create_check_constraint(
        "chk_material_publication_request_approved_action",
        "material_publication_requests",
        "approved_action IS NULL OR approved_action IN "
        "('publish_new', 'update_existing', 'keep_existing', 'publish_separate')",
    )
    op.create_check_constraint(
        "chk_material_publication_request_comparison_status",
        "material_publication_requests",
        "comparison_status IN "
        "('not_required', 'pending', 'same_material', "
        "'candidate_update', 'different_material')",
    )
    op.create_check_constraint(
        "chk_material_publication_request_type",
        "material_publication_requests",
        "request_type IN ('new_material', 'update_candidate')",
    )
    op.create_check_constraint(
        "chk_material_publication_request_update_target",
        "material_publication_requests",
        "(request_type != 'update_candidate') OR "
        "(target_public_material_id IS NOT NULL)",
    )

    op.add_column(
        "public_materials",
        sa.Column(
            "version",
            sa.Integer(),
            server_default="1",
            nullable=False,
        ),
    )
    op.add_column(
        "public_materials",
        sa.Column(
            "removed_by",
            sa.Integer(),
            nullable=True,
        ),
    )
    op.add_column(
        "public_materials",
        sa.Column(
            "removed_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
    )
    op.add_column(
        "public_materials",
        sa.Column(
            "removal_reason",
            sa.Text(),
            nullable=True,
        ),
    )

    op.create_index(
        "ix_public_materials_version",
        "public_materials",
        ["version"],
        unique=False,
    )
    op.create_index(
        "ix_public_materials_removed_by",
        "public_materials",
        ["removed_by"],
        unique=False,
    )
    op.create_index(
        "ix_public_materials_removed_at",
        "public_materials",
        ["removed_at"],
        unique=False,
    )
    op.create_index(
        "ix_public_materials_updated_at",
        "public_materials",
        ["updated_at"],
        unique=False,
    )

    op.alter_column(
        "public_materials",
        "version",
        server_default=None,
        existing_type=sa.Integer(),
        existing_nullable=False,
    )

    op.create_foreign_key(
        "fk_public_materials_removed_by_users",
        "public_materials",
        "users",
        ["removed_by"],
        ["id"],
        ondelete="SET NULL",
    )

    op.create_check_constraint(
        "chk_public_material_removed_visibility",
        "public_materials",
        "(status != 'removed') OR (is_visible = false)",
    )
    op.create_check_constraint(
        "chk_public_material_version",
        "public_materials",
        "version >= 1",
    )

    op.add_column(
        "teacher_materials",
        sa.Column(
            "version",
            sa.Integer(),
            server_default="1",
            nullable=False,
        ),
    )
    op.add_column(
        "teacher_materials",
        sa.Column(
            "status",
            sa.String(length=30),
            server_default="active",
            nullable=False,
        ),
    )
    op.add_column(
        "teacher_materials",
        sa.Column(
            "updated_by",
            sa.Integer(),
            nullable=True,
        ),
    )
    op.add_column(
        "teacher_materials",
        sa.Column(
            "removed_by",
            sa.Integer(),
            nullable=True,
        ),
    )
    op.add_column(
        "teacher_materials",
        sa.Column(
            "removed_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
    )
    op.add_column(
        "teacher_materials",
        sa.Column(
            "removal_reason",
            sa.Text(),
            nullable=True,
        ),
    )

    op.create_index(
        "ix_teacher_materials_version",
        "teacher_materials",
        ["version"],
        unique=False,
    )
    op.create_index(
        "ix_teacher_materials_status",
        "teacher_materials",
        ["status"],
        unique=False,
    )
    op.create_index(
        "ix_teacher_materials_updated_by",
        "teacher_materials",
        ["updated_by"],
        unique=False,
    )
    op.create_index(
        "ix_teacher_materials_removed_by",
        "teacher_materials",
        ["removed_by"],
        unique=False,
    )
    op.create_index(
        "ix_teacher_materials_removed_at",
        "teacher_materials",
        ["removed_at"],
        unique=False,
    )
    op.create_index(
        "ix_teacher_materials_updated_at",
        "teacher_materials",
        ["updated_at"],
        unique=False,
    )
    op.create_index(
        "ix_teacher_materials_file_hash",
        "teacher_materials",
        ["file_hash"],
        unique=False,
    )
    op.create_index(
        "ix_teacher_materials_visibility",
        "teacher_materials",
        ["visibility"],
        unique=False,
    )

    op.create_foreign_key(
        "fk_teacher_materials_updated_by_users",
        "teacher_materials",
        "users",
        ["updated_by"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        "fk_teacher_materials_removed_by_users",
        "teacher_materials",
        "users",
        ["removed_by"],
        ["id"],
        ondelete="SET NULL",
    )

    op.create_check_constraint(
        "chk_teacher_material_removed_active",
        "teacher_materials",
        "(status != 'removed') OR (is_active = false)",
    )
    op.create_check_constraint(
        "chk_teacher_material_status",
        "teacher_materials",
        "status IN ('active', 'hidden', 'removed')",
    )
    op.create_check_constraint(
        "chk_teacher_material_version",
        "teacher_materials",
        "version >= 1",
    )


def downgrade() -> None:
    op.drop_constraint(
        "chk_teacher_material_version",
        "teacher_materials",
        type_="check",
    )
    op.drop_constraint(
        "chk_teacher_material_status",
        "teacher_materials",
        type_="check",
    )
    op.drop_constraint(
        "chk_teacher_material_removed_active",
        "teacher_materials",
        type_="check",
    )
    op.drop_constraint(
        "fk_teacher_materials_removed_by_users",
        "teacher_materials",
        type_="foreignkey",
    )
    op.drop_constraint(
        "fk_teacher_materials_updated_by_users",
        "teacher_materials",
        type_="foreignkey",
    )

    op.drop_index(
        "ix_teacher_materials_visibility",
        table_name="teacher_materials",
    )
    op.drop_index(
        "ix_teacher_materials_file_hash",
        table_name="teacher_materials",
    )
    op.drop_index(
        "ix_teacher_materials_updated_at",
        table_name="teacher_materials",
    )
    op.drop_index(
        "ix_teacher_materials_removed_at",
        table_name="teacher_materials",
    )
    op.drop_index(
        "ix_teacher_materials_removed_by",
        table_name="teacher_materials",
    )
    op.drop_index(
        "ix_teacher_materials_updated_by",
        table_name="teacher_materials",
    )
    op.drop_index(
        "ix_teacher_materials_status",
        table_name="teacher_materials",
    )
    op.drop_index(
        "ix_teacher_materials_version",
        table_name="teacher_materials",
    )

    op.drop_column(
        "teacher_materials",
        "removal_reason",
    )
    op.drop_column(
        "teacher_materials",
        "removed_at",
    )
    op.drop_column(
        "teacher_materials",
        "removed_by",
    )
    op.drop_column(
        "teacher_materials",
        "updated_by",
    )
    op.drop_column(
        "teacher_materials",
        "status",
    )
    op.drop_column(
        "teacher_materials",
        "version",
    )

    op.drop_constraint(
        "chk_public_material_version",
        "public_materials",
        type_="check",
    )
    op.drop_constraint(
        "chk_public_material_removed_visibility",
        "public_materials",
        type_="check",
    )
    op.drop_constraint(
        "fk_public_materials_removed_by_users",
        "public_materials",
        type_="foreignkey",
    )

    op.drop_index(
        "ix_public_materials_updated_at",
        table_name="public_materials",
    )
    op.drop_index(
        "ix_public_materials_removed_at",
        table_name="public_materials",
    )
    op.drop_index(
        "ix_public_materials_removed_by",
        table_name="public_materials",
    )
    op.drop_index(
        "ix_public_materials_version",
        table_name="public_materials",
    )

    op.drop_column(
        "public_materials",
        "removal_reason",
    )
    op.drop_column(
        "public_materials",
        "removed_at",
    )
    op.drop_column(
        "public_materials",
        "removed_by",
    )
    op.drop_column(
        "public_materials",
        "version",
    )

    op.drop_constraint(
        "chk_material_publication_request_update_target",
        "material_publication_requests",
        type_="check",
    )
    op.drop_constraint(
        "chk_material_publication_request_type",
        "material_publication_requests",
        type_="check",
    )
    op.drop_constraint(
        "chk_material_publication_request_comparison_status",
        "material_publication_requests",
        type_="check",
    )
    op.drop_constraint(
        "chk_material_publication_request_approved_action",
        "material_publication_requests",
        type_="check",
    )

    op.drop_constraint(
        "fk_material_publication_requests_approved_public_material",
        "material_publication_requests",
        type_="foreignkey",
    )
    op.drop_constraint(
        "fk_material_publication_requests_target_public_material",
        "material_publication_requests",
        type_="foreignkey",
    )

    op.drop_index(
        "ix_material_publication_requests_updated_at",
        table_name="material_publication_requests",
    )
    op.drop_index(
        "ix_material_publication_requests_reviewed_at",
        table_name="material_publication_requests",
    )
    op.drop_index(
        "ix_material_publication_requests_approved_public_material_id",
        table_name="material_publication_requests",
    )
    op.drop_index(
        "ix_material_publication_requests_approved_action",
        table_name="material_publication_requests",
    )
    op.drop_index(
        "ix_material_publication_requests_comparison_status",
        table_name="material_publication_requests",
    )
    op.drop_index(
        "ix_material_publication_requests_target_public_material_id",
        table_name="material_publication_requests",
    )
    op.drop_index(
        "ix_material_publication_requests_request_type",
        table_name="material_publication_requests",
    )

    op.drop_column(
        "material_publication_requests",
        "proposed_description",
    )
    op.drop_column(
        "material_publication_requests",
        "proposed_title",
    )
    op.drop_column(
        "material_publication_requests",
        "approved_public_material_id",
    )
    op.drop_column(
        "material_publication_requests",
        "approved_action",
    )
    op.drop_column(
        "material_publication_requests",
        "comparison_status",
    )
    op.drop_column(
        "material_publication_requests",
        "target_public_material_id",
    )
    op.drop_column(
        "material_publication_requests",
        "request_type",
    )

    op.drop_constraint(
        "chk_group_material_version",
        "group_materials",
        type_="check",
    )
    op.drop_constraint(
        "chk_group_material_status",
        "group_materials",
        type_="check",
    )
    op.drop_constraint(
        "chk_group_material_size",
        "group_materials",
        type_="check",
    )
    op.drop_constraint(
        "chk_group_material_removed_active",
        "group_materials",
        type_="check",
    )

    op.drop_constraint(
        "fk_group_materials_removed_by_users",
        "group_materials",
        type_="foreignkey",
    )
    op.drop_constraint(
        "fk_group_materials_updated_by_users",
        "group_materials",
        type_="foreignkey",
    )

    op.drop_index(
        "ix_group_materials_created_at",
        table_name="group_materials",
    )
    op.drop_index(
        "ix_group_materials_updated_at",
        table_name="group_materials",
    )
    op.drop_index(
        "ix_group_materials_removed_at",
        table_name="group_materials",
    )
    op.drop_index(
        "ix_group_materials_removed_by",
        table_name="group_materials",
    )
    op.drop_index(
        "ix_group_materials_updated_by",
        table_name="group_materials",
    )
    op.drop_index(
        "ix_group_materials_is_active",
        table_name="group_materials",
    )
    op.drop_index(
        "ix_group_materials_status",
        table_name="group_materials",
    )
    op.drop_index(
        "ix_group_materials_version",
        table_name="group_materials",
    )

    op.alter_column(
        "group_materials",
        "size",
        existing_type=sa.BigInteger(),
        type_=sa.Integer(),
        existing_nullable=False,
    )
    op.alter_column(
        "group_materials",
        "file_path",
        existing_type=sa.String(length=1000),
        type_=sa.String(length=500),
        existing_nullable=False,
    )
    op.alter_column(
        "group_materials",
        "stored_name",
        existing_type=sa.String(length=500),
        type_=sa.String(length=255),
        existing_nullable=False,
    )

    op.drop_column(
        "group_materials",
        "updated_at",
    )
    op.drop_column(
        "group_materials",
        "removal_reason",
    )
    op.drop_column(
        "group_materials",
        "removed_at",
    )
    op.drop_column(
        "group_materials",
        "removed_by",
    )
    op.drop_column(
        "group_materials",
        "updated_by",
    )
    op.drop_column(
        "group_materials",
        "is_active",
    )
    op.drop_column(
        "group_materials",
        "status",
    )
    op.drop_column(
        "group_materials",
        "version",
    )