"""add quiz assignments and attempt snapshots

Revision ID: e913275afd2b
Revises: a031e252e978
Create Date: 2026-08-20 18:55:38.997909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e913275afd2b'
down_revision: Union[str, Sequence[str], None] = 'a031e252e978'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quiz_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('course', sa.String(length=100), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('selection_mode', sa.String(length=30), nullable=False),
    sa.Column('selected_arguments', sa.JSON(), nullable=False),
    sa.Column('selected_question_ids', sa.JSON(), nullable=False),
    sa.Column('question_count', sa.Integer(), nullable=False),
    sa.Column('time_limit_seconds', sa.Integer(), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quiz_assignments_course'), 'quiz_assignments', ['course'], unique=False)
    op.create_index(op.f('ix_quiz_assignments_department'), 'quiz_assignments', ['department'], unique=False)
    op.create_index(op.f('ix_quiz_assignments_due_at'), 'quiz_assignments', ['due_at'], unique=False)
    op.create_index(op.f('ix_quiz_assignments_id'), 'quiz_assignments', ['id'], unique=False)
    op.create_index(op.f('ix_quiz_assignments_is_active'), 'quiz_assignments', ['is_active'], unique=False)
    op.create_index(op.f('ix_quiz_assignments_selection_mode'), 'quiz_assignments', ['selection_mode'], unique=False)
    op.create_index(op.f('ix_quiz_assignments_subject'), 'quiz_assignments', ['subject'], unique=False)
    op.create_index(op.f('ix_quiz_assignments_subject_id'), 'quiz_assignments', ['subject_id'], unique=False)
    op.create_index(op.f('ix_quiz_assignments_teacher_id'), 'quiz_assignments', ['teacher_id'], unique=False)
    op.create_table('quiz_assignment_recipients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['quiz_assignments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['study_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assignment_id', 'group_id', name='uq_quiz_assignment_recipient_group'),
    sa.UniqueConstraint('assignment_id', 'user_id', name='uq_quiz_assignment_recipient_user')
    )
    op.create_index(op.f('ix_quiz_assignment_recipients_assignment_id'), 'quiz_assignment_recipients', ['assignment_id'], unique=False)
    op.create_index(op.f('ix_quiz_assignment_recipients_group_id'), 'quiz_assignment_recipients', ['group_id'], unique=False)
    op.create_index(op.f('ix_quiz_assignment_recipients_id'), 'quiz_assignment_recipients', ['id'], unique=False)
    op.create_index(op.f('ix_quiz_assignment_recipients_user_id'), 'quiz_assignment_recipients', ['user_id'], unique=False)
    op.create_table('quiz_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('course', sa.String(length=100), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('selected_arguments', sa.JSON(), nullable=False),
    sa.Column('question_ids', sa.JSON(), nullable=False),
    sa.Column('questions_snapshot', sa.JSON(), nullable=False),
    sa.Column('question_count', sa.Integer(), nullable=False),
    sa.Column('correct_count', sa.Integer(), nullable=False),
    sa.Column('wrong_count', sa.Integer(), nullable=False),
    sa.Column('unanswered_count', sa.Integer(), nullable=False),
    sa.Column('percentage', sa.Float(), nullable=False),
    sa.Column('time_limit_seconds', sa.Integer(), nullable=True),
    sa.Column('elapsed_seconds', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_hidden_from_history', sa.Boolean(), nullable=False),
    sa.Column('hidden_from_history_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hidden_from_history_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['quiz_assignments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['hidden_from_history_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'assignment_id', name='uq_quiz_attempt_user_assignment')
    )
    op.create_index(op.f('ix_quiz_attempts_assignment_id'), 'quiz_attempts', ['assignment_id'], unique=False)
    op.create_index(op.f('ix_quiz_attempts_course'), 'quiz_attempts', ['course'], unique=False)
    op.create_index(op.f('ix_quiz_attempts_department'), 'quiz_attempts', ['department'], unique=False)
    op.create_index(op.f('ix_quiz_attempts_id'), 'quiz_attempts', ['id'], unique=False)
    op.create_index(op.f('ix_quiz_attempts_is_deleted'), 'quiz_attempts', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_quiz_attempts_is_hidden_from_history'), 'quiz_attempts', ['is_hidden_from_history'], unique=False)
    op.create_index(op.f('ix_quiz_attempts_status'), 'quiz_attempts', ['status'], unique=False)
    op.create_index(op.f('ix_quiz_attempts_subject'), 'quiz_attempts', ['subject'], unique=False)
    op.create_index(op.f('ix_quiz_attempts_user_id'), 'quiz_attempts', ['user_id'], unique=False)
    op.create_table('quiz_attempt_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.String(length=100), nullable=False),
    sa.Column('argument', sa.String(length=255), nullable=True),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('attachments_snapshot', sa.JSON(), nullable=False),
    sa.Column('options_snapshot', sa.JSON(), nullable=False),
    sa.Column('selected_option_id', sa.String(length=30), nullable=True),
    sa.Column('selected_option_text', sa.Text(), nullable=True),
    sa.Column('correct_option_id', sa.String(length=30), nullable=False),
    sa.Column('correct_option_text', sa.Text(), nullable=False),
    sa.Column('is_answered', sa.Boolean(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('response_time_seconds', sa.Integer(), nullable=True),
    sa.Column('formal_explanation', sa.Text(), nullable=True),
    sa.Column('informal_explanation', sa.Text(), nullable=True),
    sa.Column('selected_answer_explanation', sa.Text(), nullable=True),
    sa.Column('correct_answer_explanation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['quiz_attempts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quiz_attempt_answers_argument'), 'quiz_attempt_answers', ['argument'], unique=False)
    op.create_index(op.f('ix_quiz_attempt_answers_attempt_id'), 'quiz_attempt_answers', ['attempt_id'], unique=False)
    op.create_index(op.f('ix_quiz_attempt_answers_id'), 'quiz_attempt_answers', ['id'], unique=False)
    op.create_index(op.f('ix_quiz_attempt_answers_question_id'), 'quiz_attempt_answers', ['question_id'], unique=False)
    op.create_check_constraint('chk_group_news_content', 'group_news', 'length(trim(content)) > 0')
    op.create_check_constraint('chk_group_news_report_reason', 'group_news_reports', "reason IN ('spam', 'harassment', 'hate_speech', 'sexual_content', 'violence', 'misinformation', 'privacy_violation', 'impersonation', 'illegal_content', 'other')")
    op.create_check_constraint('chk_user_block_not_self', 'user_blocks', 'blocker_user_id <> blocked_user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('chk_user_block_not_self', 'user_blocks', type_='check')
    op.drop_constraint('chk_group_news_report_reason', 'group_news_reports', type_='check')
    op.drop_constraint('chk_group_news_content', 'group_news', type_='check')
    op.drop_index(op.f('ix_quiz_attempt_answers_question_id'), table_name='quiz_attempt_answers')
    op.drop_index(op.f('ix_quiz_attempt_answers_id'), table_name='quiz_attempt_answers')
    op.drop_index(op.f('ix_quiz_attempt_answers_attempt_id'), table_name='quiz_attempt_answers')
    op.drop_index(op.f('ix_quiz_attempt_answers_argument'), table_name='quiz_attempt_answers')
    op.drop_table('quiz_attempt_answers')
    op.drop_index(op.f('ix_quiz_attempts_user_id'), table_name='quiz_attempts')
    op.drop_index(op.f('ix_quiz_attempts_subject'), table_name='quiz_attempts')
    op.drop_index(op.f('ix_quiz_attempts_status'), table_name='quiz_attempts')
    op.drop_index(op.f('ix_quiz_attempts_is_hidden_from_history'), table_name='quiz_attempts')
    op.drop_index(op.f('ix_quiz_attempts_is_deleted'), table_name='quiz_attempts')
    op.drop_index(op.f('ix_quiz_attempts_id'), table_name='quiz_attempts')
    op.drop_index(op.f('ix_quiz_attempts_department'), table_name='quiz_attempts')
    op.drop_index(op.f('ix_quiz_attempts_course'), table_name='quiz_attempts')
    op.drop_index(op.f('ix_quiz_attempts_assignment_id'), table_name='quiz_attempts')
    op.drop_table('quiz_attempts')
    op.drop_index(op.f('ix_quiz_assignment_recipients_user_id'), table_name='quiz_assignment_recipients')
    op.drop_index(op.f('ix_quiz_assignment_recipients_id'), table_name='quiz_assignment_recipients')
    op.drop_index(op.f('ix_quiz_assignment_recipients_group_id'), table_name='quiz_assignment_recipients')
    op.drop_index(op.f('ix_quiz_assignment_recipients_assignment_id'), table_name='quiz_assignment_recipients')
    op.drop_table('quiz_assignment_recipients')
    op.drop_index(op.f('ix_quiz_assignments_teacher_id'), table_name='quiz_assignments')
    op.drop_index(op.f('ix_quiz_assignments_subject_id'), table_name='quiz_assignments')
    op.drop_index(op.f('ix_quiz_assignments_subject'), table_name='quiz_assignments')
    op.drop_index(op.f('ix_quiz_assignments_selection_mode'), table_name='quiz_assignments')
    op.drop_index(op.f('ix_quiz_assignments_is_active'), table_name='quiz_assignments')
    op.drop_index(op.f('ix_quiz_assignments_id'), table_name='quiz_assignments')
    op.drop_index(op.f('ix_quiz_assignments_due_at'), table_name='quiz_assignments')
    op.drop_index(op.f('ix_quiz_assignments_department'), table_name='quiz_assignments')
    op.drop_index(op.f('ix_quiz_assignments_course'), table_name='quiz_assignments')
    op.drop_table('quiz_assignments')
    # ### end Alembic commands ###
