import 'package:flutter/material.dart';


/// Palette di StudentLab come [ThemeExtension].
///
/// Ogni tema usa gli STESSI nomi di [AppColors]; cambiano solo i valori.
/// Il tema iniziale è [AppPalette.kiwi]. Per un nuovo tema basta creare
/// un'altra istanza, ad esempio `AppPalette.night.copyWith(...)`.
///
/// Nei widget nuovi leggi i colori con `context.palette.eleganceMidnight`
/// invece di `AppColors.eleganceMidnight`, così il cambio tema funziona
/// senza toccare il codice. I widget esistenti possono migrare un po' alla volta.
@immutable
class AppPalette extends ThemeExtension<AppPalette> {
  final Color brandNightBlue;
  final Color secondaryNightBlue;
  final Color deepOcean;
  final Color darkElegance;
  final Color eleganceSoftNight;
  final Color eleganceMidnight;
  final Color eleganceDeepNavy;
  final Color eleganceShadow;
  final Color eleganceObsidian;
  final Color slateMidnight;
  final Color royalIndigo;
  final Color electricBlue;
  final Color vividSapphire;
  final Color lavenderBlue;
  final Color materialBlue;
  final Color materialNavy;
  final Color materialSteel;
  final Color materialSky;
  final Color socialBlue;
  final Color socialIndigo;
  final Color socialCobalt;
  final Color socialSky;
  final Color studentBlue;
  final Color studentSteel;
  final Color teacherIndigo;
  final Color teacherNavy;
  final Color availableBlue;
  final Color availableGreen;
  final Color pendingAmber;
  final Color charcoalGrey;
  final Color slateGrey;
  final Color graphite;
  final Color darkSlate;
  final Color mediumSlate;
  final Color lightSlate;
  final Color skyBlue;
  final Color diamondDust;
  final Color iceBlue;
  final Color steelBlue;
  final Color pureWhite;
  final Color pearlWhite;
  final Color mistWhite;
  final Color opaqueWhite;
  final Color translucentWhite;
  final Color correct;
  final Color wrong;
  final Color adminCyan;
  final Color adminBlue;
  final Color adminIndigo;
  final Color adminGreen;
  final Color adminAmber;
  final Color adminMagenta;
  final Color adminCoral;
  final Color surface;
  final Color surfaceStrong;
  final Color surfaceSoft;
  final Color textPrimary;
  final Color textSecondary;
  final Color textMuted;
  final Color divider;
  final Color surfaceBorder;

  const AppPalette({
    required this.brandNightBlue,
    required this.secondaryNightBlue,
    required this.deepOcean,
    required this.darkElegance,
    required this.eleganceSoftNight,
    required this.eleganceMidnight,
    required this.eleganceDeepNavy,
    required this.eleganceShadow,
    required this.eleganceObsidian,
    required this.slateMidnight,
    required this.royalIndigo,
    required this.electricBlue,
    required this.vividSapphire,
    required this.lavenderBlue,
    required this.materialBlue,
    required this.materialNavy,
    required this.materialSteel,
    required this.materialSky,
    required this.socialBlue,
    required this.socialIndigo,
    required this.socialCobalt,
    required this.socialSky,
    required this.studentBlue,
    required this.studentSteel,
    required this.teacherIndigo,
    required this.teacherNavy,
    required this.availableBlue,
    required this.availableGreen,
    required this.pendingAmber,
    required this.charcoalGrey,
    required this.slateGrey,
    required this.graphite,
    required this.darkSlate,
    required this.mediumSlate,
    required this.lightSlate,
    required this.skyBlue,
    required this.diamondDust,
    required this.iceBlue,
    required this.steelBlue,
    required this.pureWhite,
    required this.pearlWhite,
    required this.mistWhite,
    required this.opaqueWhite,
    required this.translucentWhite,
    required this.correct,
    required this.wrong,
    required this.adminCyan,
    required this.adminBlue,
    required this.adminIndigo,
    required this.adminGreen,
    required this.adminAmber,
    required this.adminMagenta,
    required this.adminCoral,
    required this.surface,
    required this.surfaceStrong,
    required this.surfaceSoft,
    required this.textPrimary,
    required this.textSecondary,
    required this.textMuted,
    required this.divider,
    required this.surfaceBorder,
  });

  /// Palette in uso. La imposta StudentLabThemeController; `AppColors.x`
  /// legge da qui, quindi cambiando tema cambiano i colori di tutta l'app.
  static AppPalette current = kiwi;

  /// True quando il tema attivo è chiaro (testo scuro su fondo chiaro).
  static bool currentIsLight = true;

  static const AppPalette night = AppPalette(
    brandNightBlue: Color(0xFF1C2841),
    secondaryNightBlue: Color(0xFF1B263B),
    deepOcean: Color(0xFF0F1C3F),
    darkElegance: Color(0xFF0C0F1A),
    eleganceSoftNight: Color(0xFF0E1220),
    eleganceMidnight: Color(0xFF111526),
    eleganceDeepNavy: Color(0xFF14192D),
    eleganceShadow: Color(0xFF070911),
    eleganceObsidian: Color(0xFF0B0D14),
    slateMidnight: Color(0xFF1A237E),
    royalIndigo: Color(0xFF283593),
    electricBlue: Color(0xFF303F9F),
    vividSapphire: Color(0xFF3949AB),
    lavenderBlue: Color(0xFF5C6BC0),
    materialBlue: Color(0xFF263A5F),
    materialNavy: Color(0xFF1E3152),
    materialSteel: Color(0xFF344B6B),
    materialSky: Color(0xFF4F7CAC),
    socialBlue: Color(0xFF304A70),
    socialIndigo: Color(0xFF3F4F88),
    socialCobalt: Color(0xFF405D8C),
    socialSky: Color(0xFF5B8CC0),
    studentBlue: Color(0xFF42658F),
    studentSteel: Color(0xFF52769F),
    teacherIndigo: Color(0xFF454B7A),
    teacherNavy: Color(0xFF30385F),
    availableBlue: Color(0xFF4E7FAF),
    availableGreen: Color(0xFF3F7650),
    pendingAmber: Color(0xFF9A7838),
    charcoalGrey: Color(0xFF1A1F3A),
    slateGrey: Color(0xFF263238),
    graphite: Color(0xFF212121),
    darkSlate: Color(0xFF424242),
    mediumSlate: Color(0xFF757575),
    lightSlate: Color(0xFFBDBDBD),
    skyBlue: Color(0xFF64B5F6),
    diamondDust: Color(0xFFBBDEFB),
    iceBlue: Color(0xFFE3F2FD),
    steelBlue: Color(0xFF90A4AE),
    pureWhite: Color(0xFFFFFFFF),
    pearlWhite: Color(0xFFFAFAFA),
    mistWhite: Color(0xFFF5F5F5),
    opaqueWhite: Color.fromRGBO(255, 255, 255, 0.9),
    translucentWhite: Color.fromRGBO(255, 255, 255, 0.15),
    correct: Color.fromARGB(255, 4, 89, 8),
    wrong: Color.fromARGB(255, 68, 1, 1),
    adminCyan: Color(0xFF35D0E6),
    adminBlue: Color(0xFF5B8CFF),
    adminIndigo: Color(0xFF7A78FF),
    adminGreen: Color(0xFF54D99B),
    adminAmber: Color(0xFFF4B860),
    adminMagenta: Color(0xFFE86FCB),
    adminCoral: Color(0xFFFF7D7D),
    surface: Color(0xFF14192D),
    surfaceStrong: Color(0xFF111526),
    surfaceSoft: Color(0xFF0E1220),
    textPrimary: Color(0xFFFFFFFF),
    textSecondary: Color(0xB3FFFFFF),
    textMuted: Color(0x73FFFFFF),
    divider: Color(0x14FFFFFF),
    surfaceBorder: Color(0x1FFFFFFF),
  );

  /// Ardesia (scuro): Grafite con verde acqua.
  static const AppPalette ardesia = AppPalette(
    brandNightBlue: Color(0xFF1F2B29),
    secondaryNightBlue: Color(0xFF1D2826),
    deepOcean: Color(0xFF0F2422),
    darkElegance: Color(0xFF101312),
    eleganceSoftNight: Color(0xFF121615),
    eleganceMidnight: Color(0xFF161B1A),
    eleganceDeepNavy: Color(0xFF1B2120),
    eleganceShadow: Color(0xFF070908),
    eleganceObsidian: Color(0xFF0C0F0E),
    slateMidnight: Color(0xFF173F3A),
    royalIndigo: Color(0xFF1F4C46),
    electricBlue: Color(0xFF265A53),
    vividSapphire: Color(0xFF2E6B62),
    lavenderBlue: Color(0xFF8C84D8),
    materialBlue: Color(0xFF26433F),
    materialNavy: Color(0xFF1E3834),
    materialSteel: Color(0xFF35524D),
    materialSky: Color(0xFF4FA396),
    socialBlue: Color(0xFF2F4E49),
    socialIndigo: Color(0xFF4A4F86),
    socialCobalt: Color(0xFF3F6660),
    socialSky: Color(0xFF57B3A6),
    studentBlue: Color(0xFF3F7A70),
    studentSteel: Color(0xFF4F8C82),
    teacherIndigo: Color(0xFF5A527E),
    teacherNavy: Color(0xFF3A3558),
    availableBlue: Color(0xFF4FA396),
    availableGreen: Color(0xFF4C8A5A),
    pendingAmber: Color(0xFFA8823A),
    charcoalGrey: Color(0xFF1C2322),
    slateGrey: Color(0xFF263230),
    graphite: Color(0xFF212121),
    darkSlate: Color(0xFF424242),
    mediumSlate: Color(0xFF757575),
    lightSlate: Color(0xFFBDBDBD),
    skyBlue: Color(0xFF5FD3C4),
    diamondDust: Color(0xFFBFEFE8),
    iceBlue: Color(0xFFE6FAF7),
    steelBlue: Color(0xFF9AABA7),
    pureWhite: Color(0xFFFFFFFF),
    pearlWhite: Color(0xFFFAFAFA),
    mistWhite: Color(0xFFF5F5F5),
    opaqueWhite: Color(0xE6FFFFFF),
    translucentWhite: Color(0x26FFFFFF),
    correct: Color(0xFF2E7D32),
    wrong: Color(0xFF7A1F1F),
    adminCyan: Color(0xFF4CC9E8),
    adminBlue: Color(0xFF6E9BFF),
    adminIndigo: Color(0xFF9A8CFF),
    adminGreen: Color(0xFF8BD86A),
    adminAmber: Color(0xFFF2B45A),
    adminMagenta: Color(0xFFE77BC9),
    adminCoral: Color(0xFFFF8A7A),
    surface: Color(0xFF1B2120),
    surfaceStrong: Color(0xFF161B1A),
    surfaceSoft: Color(0xFF121615),
    textPrimary: Color(0xFFFFFFFF),
    textSecondary: Color(0xB3FFFFFF),
    textMuted: Color(0x73FFFFFF),
    divider: Color(0x14FFFFFF),
    surfaceBorder: Color(0x1FFFFFFF),
  );

  /// Terra (scuro): Marrone caldo, riposante.
  static const AppPalette terra = AppPalette(
    brandNightBlue: Color(0xFF33261F),
    secondaryNightBlue: Color(0xFF2F231C),
    deepOcean: Color(0xFF2A1C14),
    darkElegance: Color(0xFF16110E),
    eleganceSoftNight: Color(0xFF19130F),
    eleganceMidnight: Color(0xFF1E1713),
    eleganceDeepNavy: Color(0xFF251C17),
    eleganceShadow: Color(0xFF0A0706),
    eleganceObsidian: Color(0xFF120E0B),
    slateMidnight: Color(0xFF4A2E20),
    royalIndigo: Color(0xFF573526),
    electricBlue: Color(0xFF633D2B),
    vividSapphire: Color(0xFF704531),
    lavenderBlue: Color(0xFFA58CC0),
    materialBlue: Color(0xFF4A3428),
    materialNavy: Color(0xFF3E2B21),
    materialSteel: Color(0xFF5A4336),
    materialSky: Color(0xFFB5836A),
    socialBlue: Color(0xFF4E3829),
    socialIndigo: Color(0xFF5A4760),
    socialCobalt: Color(0xFF6A4A36),
    socialSky: Color(0xFFC68F74),
    studentBlue: Color(0xFF8A6A52),
    studentSteel: Color(0xFF9C7A60),
    teacherIndigo: Color(0xFF6E5A78),
    teacherNavy: Color(0xFF4B3D55),
    availableBlue: Color(0xFFB5836A),
    availableGreen: Color(0xFF6B8A4E),
    pendingAmber: Color(0xFFA99032),
    charcoalGrey: Color(0xFF241B16),
    slateGrey: Color(0xFF2E2622),
    graphite: Color(0xFF212121),
    darkSlate: Color(0xFF424242),
    mediumSlate: Color(0xFF757575),
    lightSlate: Color(0xFFBDBDBD),
    skyBlue: Color(0xFFD69F85),
    diamondDust: Color(0xFFF2D8CB),
    iceBlue: Color(0xFFF8EDE4),
    steelBlue: Color(0xFFB0A196),
    pureWhite: Color(0xFFFFFFFF),
    pearlWhite: Color(0xFFF7F0EA),
    mistWhite: Color(0xFFF1E8E0),
    opaqueWhite: Color(0xE6FFFFFF),
    translucentWhite: Color(0x26FFFFFF),
    correct: Color(0xFF4E7A3A),
    wrong: Color(0xFF7A2E24),
    adminCyan: Color(0xFF7EC4C4),
    adminBlue: Color(0xFF8FA7D9),
    adminIndigo: Color(0xFFA994D6),
    adminGreen: Color(0xFFA3C77A),
    adminAmber: Color(0xFFE6C15C),
    adminMagenta: Color(0xFFD38DB4),
    adminCoral: Color(0xFFD9644F),
    surface: Color(0xFF251C17),
    surfaceStrong: Color(0xFF1E1713),
    surfaceSoft: Color(0xFF19130F),
    textPrimary: Color(0xFFFFFFFF),
    textSecondary: Color(0xB3FFFFFF),
    textMuted: Color(0x73FFFFFF),
    divider: Color(0x14FFFFFF),
    surfaceBorder: Color(0x1FFFFFFF),
  );

  /// Bosco (scuro): Verde di foglie e muschio.
  static const AppPalette bosco = AppPalette(
    brandNightBlue: Color(0xFF1F2D22),
    secondaryNightBlue: Color(0xFF1D2A20),
    deepOcean: Color(0xFF2C3F2E),
    darkElegance: Color(0xFF0E1410),
    eleganceSoftNight: Color(0xFF101612),
    eleganceMidnight: Color(0xFF131B15),
    eleganceDeepNavy: Color(0xFF18221A),
    eleganceShadow: Color(0xFF060806),
    eleganceObsidian: Color(0xFF0A0E0B),
    slateMidnight: Color(0xFF2A3C2C),
    royalIndigo: Color(0xFF304532),
    electricBlue: Color(0xFF374D38),
    vividSapphire: Color(0xFF3E563D),
    lavenderBlue: Color(0xFF9288BC),
    materialBlue: Color(0xFF2E4230),
    materialNavy: Color(0xFF28392A),
    materialSteel: Color(0xFF39503A),
    materialSky: Color(0xFF709A6A),
    socialBlue: Color(0xFF334734),
    socialIndigo: Color(0xFF484E59),
    socialCobalt: Color(0xFF40593F),
    socialSky: Color(0xFF7FAF78),
    studentBlue: Color(0xFF506F4E),
    studentSteel: Color(0xFF5E825B),
    teacherIndigo: Color(0xFF5D5F75),
    teacherNavy: Color(0xFF3D454A),
    availableBlue: Color(0xFF709A6A),
    availableGreen: Color(0xFF848E46),
    pendingAmber: Color(0xFF9C7C41),
    charcoalGrey: Color(0xFF19241C),
    slateGrey: Color(0xFF313E34),
    graphite: Color(0xFF212121),
    darkSlate: Color(0xFF424242),
    mediumSlate: Color(0xFF757575),
    lightSlate: Color(0xFFBDBDBD),
    skyBlue: Color(0xFF8CC084),
    diamondDust: Color(0xFFD2EBCB),
    iceBlue: Color(0xFFE2F2DD),
    steelBlue: Color(0xFFBDCABB),
    pureWhite: Color(0xFFFFFFFF),
    pearlWhite: Color(0xFFF5F6F5),
    mistWhite: Color(0xFFECECEC),
    opaqueWhite: Color(0xE6FFFFFF),
    translucentWhite: Color(0x26FFFFFF),
    correct: Color(0xFF747B3A),
    wrong: Color(0xFF65352B),
    adminCyan: Color(0xFF6CC6C0),
    adminBlue: Color(0xFF86A9DB),
    adminIndigo: Color(0xFFA99CDA),
    adminGreen: Color(0xFFD3E06A),
    adminAmber: Color(0xFFE8B45C),
    adminMagenta: Color(0xFFD98BB5),
    adminCoral: Color(0xFFE0765F),
    surface: Color(0xFF18221A),
    surfaceStrong: Color(0xFF131B15),
    surfaceSoft: Color(0xFF101612),
    textPrimary: Color(0xFFFFFFFF),
    textSecondary: Color(0xB3FFFFFF),
    textMuted: Color(0x73FFFFFF),
    divider: Color(0x14FFFFFF),
    surfaceBorder: Color(0x1FFFFFFF),
  );

  /// Pietra (scuro): Travertino e ardesia.
  static const AppPalette pietra = AppPalette(
    brandNightBlue: Color(0xFF2B2926),
    secondaryNightBlue: Color(0xFF282623),
    deepOcean: Color(0xFF3E3B34),
    darkElegance: Color(0xFF141311),
    eleganceSoftNight: Color(0xFF161513),
    eleganceMidnight: Color(0xFF1A1917),
    eleganceDeepNavy: Color(0xFF211F1C),
    eleganceShadow: Color(0xFF090908),
    eleganceObsidian: Color(0xFF0E0E0C),
    slateMidnight: Color(0xFF3B3831),
    royalIndigo: Color(0xFF454038),
    electricBlue: Color(0xFF4F493F),
    vividSapphire: Color(0xFF585246),
    lavenderBlue: Color(0xFF8F87A9),
    materialBlue: Color(0xFF423D36),
    materialNavy: Color(0xFF38352F),
    materialSteel: Color(0xFF524C41),
    materialSky: Color(0xFFA4967A),
    socialBlue: Color(0xFF48433B),
    socialIndigo: Color(0xFF504B55),
    socialCobalt: Color(0xFF5C5548),
    socialSky: Color(0xFFBAAA8A),
    studentBlue: Color(0xFF746B59),
    studentSteel: Color(0xFF897E68),
    teacherIndigo: Color(0xFF625C6D),
    teacherNavy: Color(0xFF464249),
    availableBlue: Color(0xFFA4967A),
    availableGreen: Color(0xFF667A57),
    pendingAmber: Color(0xFF947844),
    charcoalGrey: Color(0xFF22211E),
    slateGrey: Color(0xFF3C3A37),
    graphite: Color(0xFF212121),
    darkSlate: Color(0xFF424242),
    mediumSlate: Color(0xFF757575),
    lightSlate: Color(0xFFBDBDBD),
    skyBlue: Color(0xFFCDBB98),
    diamondDust: Color(0xFFEFE6D4),
    iceBlue: Color(0xFFF5EFE3),
    steelBlue: Color(0xFFD4CFC6),
    pureWhite: Color(0xFFFFFFFF),
    pearlWhite: Color(0xFFF6F6F5),
    mistWhite: Color(0xFFECECEC),
    opaqueWhite: Color(0xE6FFFFFF),
    translucentWhite: Color(0x26FFFFFF),
    correct: Color(0xFF56694A),
    wrong: Color(0xFF5E372F),
    adminCyan: Color(0xFF7FB7BA),
    adminBlue: Color(0xFF8FA3C4),
    adminIndigo: Color(0xFFA59BC4),
    adminGreen: Color(0xFF9CBF86),
    adminAmber: Color(0xFFD9AE5F),
    adminMagenta: Color(0xFFC590A8),
    adminCoral: Color(0xFFD27A68),
    surface: Color(0xFF211F1C),
    surfaceStrong: Color(0xFF1A1917),
    surfaceSoft: Color(0xFF161513),
    textPrimary: Color(0xFFFFFFFF),
    textSecondary: Color(0xB3FFFFFF),
    textMuted: Color(0x73FFFFFF),
    divider: Color(0x14FFFFFF),
    surfaceBorder: Color(0x1FFFFFFF),
  );

  /// Fico (scuro): Buccia viola, polpa rosa, foglia verde.
  static const AppPalette fico = AppPalette(
    brandNightBlue: Color(0xFF33233A),
    secondaryNightBlue: Color(0xFF2E2034),
    deepOcean: Color(0xFF483046),
    darkElegance: Color(0xFF150F16),
    eleganceSoftNight: Color(0xFF171118),
    eleganceMidnight: Color(0xFF1C141D),
    eleganceDeepNavy: Color(0xFF241A26),
    eleganceShadow: Color(0xFF09070A),
    eleganceObsidian: Color(0xFF0F0B10),
    slateMidnight: Color(0xFF442E44),
    royalIndigo: Color(0xFF4F3549),
    electricBlue: Color(0xFF593C4F),
    vividSapphire: Color(0xFF634255),
    lavenderBlue: Color(0xFF9A86C2),
    materialBlue: Color(0xFF4B3347),
    materialNavy: Color(0xFF412C42),
    materialSteel: Color(0xFF5D3E51),
    materialSky: Color(0xFFB3767D),
    socialBlue: Color(0xFF52374B),
    socialIndigo: Color(0xFF59476C),
    socialCobalt: Color(0xFF674557),
    socialSky: Color(0xFFCC868D),
    studentBlue: Color(0xFF815565),
    studentSteel: Color(0xFF976472),
    teacherIndigo: Color(0xFF6C5985),
    teacherNavy: Color(0xFF4F3D5F),
    availableBlue: Color(0xFFB3767D),
    availableGreen: Color(0xFF6C7D52),
    pendingAmber: Color(0xFF997A45),
    charcoalGrey: Color(0xFF281C2C),
    slateGrey: Color(0xFF43354A),
    graphite: Color(0xFF212121),
    darkSlate: Color(0xFF424242),
    mediumSlate: Color(0xFF757575),
    lightSlate: Color(0xFFBDBDBD),
    skyBlue: Color(0xFFE0939A),
    diamondDust: Color(0xFFF7D5D2),
    iceBlue: Color(0xFFFAE4E2),
    steelBlue: Color(0xFFDCC8CA),
    pureWhite: Color(0xFFFFFFFF),
    pearlWhite: Color(0xFFF6F5F6),
    mistWhite: Color(0xFFECECEC),
    opaqueWhite: Color(0xE6FFFFFF),
    translucentWhite: Color(0x26FFFFFF),
    correct: Color(0xFF5B6D43),
    wrong: Color(0xFF682B24),
    adminCyan: Color(0xFF7CC0C4),
    adminBlue: Color(0xFF8FA4DA),
    adminIndigo: Color(0xFFB29BE0),
    adminGreen: Color(0xFFA6C77A),
    adminAmber: Color(0xFFE0B45E),
    adminMagenta: Color(0xFFCF8CD0),
    adminCoral: Color(0xFFE8604F),
    surface: Color(0xFF241A26),
    surfaceStrong: Color(0xFF1C141D),
    surfaceSoft: Color(0xFF171118),
    textPrimary: Color(0xFFFFFFFF),
    textSecondary: Color(0xB3FFFFFF),
    textMuted: Color(0x73FFFFFF),
    divider: Color(0x14FFFFFF),
    surfaceBorder: Color(0x1FFFFFFF),
  );

  /// Torbiera (scuro): Torba, muschio, laghi ed erica d’Irlanda.
  static const AppPalette torbiera = AppPalette(
    brandNightBlue: Color(0xFF29291E),
    secondaryNightBlue: Color(0xFF26251C),
    deepOcean: Color(0xFF373A28),
    darkElegance: Color(0xFF12110D),
    eleganceSoftNight: Color(0xFF14130F),
    eleganceMidnight: Color(0xFF181712),
    eleganceDeepNavy: Color(0xFF1E1D17),
    eleganceShadow: Color(0xFF060604),
    eleganceObsidian: Color(0xFF0C0B09),
    slateMidnight: Color(0xFF353726),
    royalIndigo: Color(0xFF3C402B),
    electricBlue: Color(0xFF434830),
    vividSapphire: Color(0xFF4A5136),
    lavenderBlue: Color(0xFF917FAD),
    materialBlue: Color(0xFF393D2A),
    materialNavy: Color(0xFF323425),
    materialSteel: Color(0xFF454B32),
    materialSky: Color(0xFF7F935C),
    socialBlue: Color(0xFF3E432D),
    socialIndigo: Color(0xFF4F4851),
    socialCobalt: Color(0xFF4C5437),
    socialSky: Color(0xFF90A768),
    studentBlue: Color(0xFF5E6944),
    studentSteel: Color(0xFF6D7C4F),
    teacherIndigo: Color(0xFF62586B),
    teacherNavy: Color(0xFF454044),
    availableBlue: Color(0xFF7F935C),
    availableGreen: Color(0xFF4A8158),
    pendingAmber: Color(0xFF9A8237),
    charcoalGrey: Color(0xFF202018),
    slateGrey: Color(0xFF3A3A30),
    graphite: Color(0xFF212121),
    darkSlate: Color(0xFF424242),
    mediumSlate: Color(0xFF757575),
    lightSlate: Color(0xFFBDBDBD),
    skyBlue: Color(0xFF9EB872),
    diamondDust: Color(0xFFD6E4BD),
    iceBlue: Color(0xFFE4EDD4),
    steelBlue: Color(0xFFBCC3B1),
    pureWhite: Color(0xFFFFFFFF),
    pearlWhite: Color(0xFFF6F5F5),
    mistWhite: Color(0xFFECECEC),
    opaqueWhite: Color(0xE6FFFFFF),
    translucentWhite: Color(0x26FFFFFF),
    correct: Color(0xFF3D704C),
    wrong: Color(0xFF602F23),
    adminCyan: Color(0xFF7FB3BF),
    adminBlue: Color(0xFF8FA2C8),
    adminIndigo: Color(0xFFA792C9),
    adminGreen: Color(0xFF6FCB8A),
    adminAmber: Color(0xFFE3BF4E),
    adminMagenta: Color(0xFFC98AB6),
    adminCoral: Color(0xFFD6694E),
    surface: Color(0xFF1E1D17),
    surfaceStrong: Color(0xFF181712),
    surfaceSoft: Color(0xFF14130F),
    textPrimary: Color(0xFFFFFFFF),
    textSecondary: Color(0xB3FFFFFF),
    textMuted: Color(0x73FFFFFF),
    divider: Color(0x14FFFFFF),
    surfaceBorder: Color(0x1FFFFFFF),
  );

  /// Kiwi (chiaro): Polpa verde, cuore crema, semi scuri.
  static const AppPalette kiwi = AppPalette(
    brandNightBlue: Color(0xFFE4EACB),
    secondaryNightBlue: Color(0xFFECF0DB),
    deepOcean: Color(0xFFC5D3A9),
    darkElegance: Color(0xFFF4F2E7),
    eleganceSoftNight: Color(0xFFF8F6EC),
    eleganceMidnight: Color(0xFFFFFDF6),
    eleganceDeepNavy: Color(0xFFFFFFFF),
    eleganceShadow: Color(0xFFE1DBBD),
    eleganceObsidian: Color(0xFFF7F6EE),
    slateMidnight: Color(0xFFD4DEBA),
    royalIndigo: Color(0xFFCBD7B0),
    electricBlue: Color(0xFFC2D0A6),
    vividSapphire: Color(0xFFB8CA9C),
    lavenderBlue: Color(0xFF7164B7),
    materialBlue: Color(0xFFCEDAB3),
    materialNavy: Color(0xFFD8E1BD),
    materialSteel: Color(0xFFBFCEA2),
    materialSky: Color(0xFF6E914D),
    socialBlue: Color(0xFFC8D5AD),
    socialIndigo: Color(0xFFBBBAC2),
    socialCobalt: Color(0xFFB5C798),
    socialSky: Color(0xFF598236),
    studentBlue: Color(0xFF9EB67F),
    studentSteel: Color(0xFF8AA769),
    teacherIndigo: Color(0xFFA6A2BE),
    teacherNavy: Color(0xFFC6C7C5),
    availableBlue: Color(0xFF6E914D),
    availableGreen: Color(0xFF7EAC7F),
    pendingAmber: Color(0xFFBD9A5D),
    charcoalGrey: Color(0xFFF2F4E0),
    slateGrey: Color(0xFFD5DABD),
    graphite: Color(0xFF212121),
    darkSlate: Color(0xFF424242),
    mediumSlate: Color(0xFF757575),
    lightSlate: Color(0xFFBDBDBD),
    skyBlue: Color(0xFF487622),
    diamondDust: Color(0xFF36591A),
    iceBlue: Color(0xFF32461B),
    steelBlue: Color(0xFF3D4831),
    pureWhite: Color(0xFF2B241C),
    pearlWhite: Color(0xFF332C24),
    mistWhite: Color(0xFF3B342C),
    opaqueWhite: Color(0xE62B241C),
    translucentWhite: Color(0x262B241C),
    correct: Color(0xFF286A31),
    wrong: Color(0xFFAC3427),
    adminCyan: Color(0xFF1D7A80),
    adminBlue: Color(0xFF2F5FB3),
    adminIndigo: Color(0xFF5A4BAE),
    adminGreen: Color(0xFF2F7D3A),
    adminAmber: Color(0xFFA06B12),
    adminMagenta: Color(0xFFA33F7C),
    adminCoral: Color(0xFFBF3A2B),
    surface: Color(0xFFFFFFFF),
    surfaceStrong: Color(0xFFFFFDF6),
    surfaceSoft: Color(0xFFF8F6EC),
    textPrimary: Color(0xFF2B241C),
    textSecondary: Color(0xB32B241C),
    textMuted: Color(0x732B241C),
    divider: Color(0x142B241C),
    surfaceBorder: Color(0x1F2B241C),
  );

  /// Pesca (chiaro): Buccia rosata e polpa dorata.
  static const AppPalette pesca = AppPalette(
    brandNightBlue: Color(0xFFF6E1D3),
    secondaryNightBlue: Color(0xFFF9EAE0),
    deepOcean: Color(0xFFE7C4B2),
    darkElegance: Color(0xFFFBF3EC),
    eleganceSoftNight: Color(0xFFFCF6F0),
    eleganceMidnight: Color(0xFFFFFCF8),
    eleganceDeepNavy: Color(0xFFFFFFFF),
    eleganceShadow: Color(0xFFF0D3B9),
    eleganceObsidian: Color(0xFFFDF8F4),
    slateMidnight: Color(0xFFEED2C2),
    royalIndigo: Color(0xFFEACAB8),
    electricBlue: Color(0xFFE5C1AE),
    vividSapphire: Color(0xFFE0B8A4),
    lavenderBlue: Color(0xFF7468B7),
    materialBlue: Color(0xFFEBCDBC),
    materialNavy: Color(0xFFF0D5C6),
    materialSteel: Color(0xFFE4BEAB),
    materialSky: Color(0xFFBB7456),
    socialBlue: Color(0xFFE8C7B5),
    socialIndigo: Color(0xFFC8B5C8),
    socialCobalt: Color(0xFFDFB6A1),
    socialSky: Color(0xFFB1603F),
    studentBlue: Color(0xFFD3A088),
    studentSteel: Color(0xFFC98D72),
    teacherIndigo: Color(0xFFB19FC2),
    teacherNavy: Color(0xFFD4C1CB),
    availableBlue: Color(0xFFBB7456),
    availableGreen: Color(0xFF8AAD7F),
    pendingAmber: Color(0xFFBC9A5D),
    charcoalGrey: Color(0xFFFAEEE6),
    slateGrey: Color(0xFFE7D2C5),
    graphite: Color(0xFF212121),
    darkSlate: Color(0xFF424242),
    mediumSlate: Color(0xFF757575),
    lightSlate: Color(0xFFBDBDBD),
    skyBlue: Color(0xFFA9502C),
    diamondDust: Color(0xFF8A3F20),
    iceBlue: Color(0xFF6E3821),
    steelBlue: Color(0xFF674E44),
    pureWhite: Color(0xFF3A2A24),
    pearlWhite: Color(0xFF42322C),
    mistWhite: Color(0xFF493A34),
    opaqueWhite: Color(0xE63A2A24),
    translucentWhite: Color(0x263A2A24),
    correct: Color(0xFF366C2F),
    wrong: Color(0xFFA22929),
    adminCyan: Color(0xFF1E7688),
    adminBlue: Color(0xFF3561AE),
    adminIndigo: Color(0xFF5C4FAE),
    adminGreen: Color(0xFF3F7F37),
    adminAmber: Color(0xFF9A6A10),
    adminMagenta: Color(0xFFA3406F),
    adminCoral: Color(0xFFB42E2E),
    surface: Color(0xFFFFFFFF),
    surfaceStrong: Color(0xFFFFFCF8),
    surfaceSoft: Color(0xFFFCF6F0),
    textPrimary: Color(0xFF3A2A24),
    textSecondary: Color(0xB33A2A24),
    textMuted: Color(0x733A2A24),
    divider: Color(0x143A2A24),
    surfaceBorder: Color(0x1F3A2A24),
  );

  /// Antartide (chiaro): Ghiaccio, neve e mare profondo.
  static const AppPalette antartide = AppPalette(
    brandNightBlue: Color(0xFFDAE8F1),
    secondaryNightBlue: Color(0xFFE5EFF5),
    deepOcean: Color(0xFFB5CFE1),
    darkElegance: Color(0xFFEDF3F7),
    eleganceSoftNight: Color(0xFFF1F6F9),
    eleganceMidnight: Color(0xFFF8FBFD),
    eleganceDeepNavy: Color(0xFFFFFFFF),
    eleganceShadow: Color(0xFFC3D7E4),
    eleganceObsidian: Color(0xFFF4F8FA),
    slateMidnight: Color(0xFFC7DCE9),
    royalIndigo: Color(0xFFBCD4E5),
    electricBlue: Color(0xFFB1CCE0),
    vividSapphire: Color(0xFFA6C5DB),
    lavenderBlue: Color(0xFF7064B9),
    materialBlue: Color(0xFFC0D6E6),
    materialNavy: Color(0xFFCBDEEB),
    materialSteel: Color(0xFFADCADE),
    materialSky: Color(0xFF4C89B5),
    socialBlue: Color(0xFFB8D2E3),
    socialIndigo: Color(0xFFB4B9DD),
    socialCobalt: Color(0xFFA2C2DA),
    socialSky: Color(0xFF3479AB),
    studentBlue: Color(0xFF86B0CE),
    studentSteel: Color(0xFF6EA0C4),
    teacherIndigo: Color(0xFFA0A1D3),
    teacherNavy: Color(0xFFBEC5E2),
    availableBlue: Color(0xFF4C89B5),
    availableGreen: Color(0xFF7AAB92),
    pendingAmber: Color(0xFFB49760),
    charcoalGrey: Color(0xFFE9F2F7),
    slateGrey: Color(0xFFCAD9E2),
    graphite: Color(0xFF212121),
    darkSlate: Color(0xFF424242),
    mediumSlate: Color(0xFF757575),
    lightSlate: Color(0xFFBDBDBD),
    skyBlue: Color(0xFF1F6BA3),
    diamondDust: Color(0xFF164F7A),
    iceBlue: Color(0xFF164164),
    steelBlue: Color(0xFF394F61),
    pureWhite: Color(0xFF15273A),
    pearlWhite: Color(0xFF1E2F42),
    mistWhite: Color(0xFF263749),
    opaqueWhite: Color(0xE615273A),
    translucentWhite: Color(0x2615273A),
    correct: Color(0xFF276942),
    wrong: Color(0xFF9E3028),
    adminCyan: Color(0xFF0E7A8A),
    adminBlue: Color(0xFF3A52B0),
    adminIndigo: Color(0xFF5A4BAE),
    adminGreen: Color(0xFF2E7B4E),
    adminAmber: Color(0xFF95660F),
    adminMagenta: Color(0xFF983E78),
    adminCoral: Color(0xFFB0352D),
    surface: Color(0xFFFFFFFF),
    surfaceStrong: Color(0xFFF8FBFD),
    surfaceSoft: Color(0xFFF1F6F9),
    textPrimary: Color(0xFF15273A),
    textSecondary: Color(0xB315273A),
    textMuted: Color(0x7315273A),
    divider: Color(0x1415273A),
    surfaceBorder: Color(0x1F15273A),
  );

  /// Cocco (chiaro): Polpa bianca, guscio bruno, palma.
  static const AppPalette cocco = AppPalette(
    brandNightBlue: Color(0xFFEADFCF),
    secondaryNightBlue: Color(0xFFF0E9DD),
    deepOcean: Color(0xFFD4C3AF),
    darkElegance: Color(0xFFF6F1E8),
    eleganceSoftNight: Color(0xFFF9F5EE),
    eleganceMidnight: Color(0xFFFFFDF9),
    eleganceDeepNavy: Color(0xFFFFFFFF),
    eleganceShadow: Color(0xFFE5D6BC),
    eleganceObsidian: Color(0xFFF9F5EF),
    slateMidnight: Color(0xFFDFD1BF),
    royalIndigo: Color(0xFFD8C8B6),
    electricBlue: Color(0xFFD1C0AC),
    vividSapphire: Color(0xFFCBB8A2),
    lavenderBlue: Color(0xFF7266A9),
    materialBlue: Color(0xFFDACBB9),
    materialNavy: Color(0xFFE1D4C2),
    materialSteel: Color(0xFFCFBDA9),
    materialSky: Color(0xFF957558),
    socialBlue: Color(0xFFD6C6B2),
    socialIndigo: Color(0xFFBFB4C0),
    socialCobalt: Color(0xFFC8B59F),
    socialSky: Color(0xFF866242),
    studentBlue: Color(0xFFB8A087),
    studentSteel: Color(0xFFA98D73),
    teacherIndigo: Color(0xFFAA9EB9),
    teacherNavy: Color(0xFFCBBFC4),
    availableBlue: Color(0xFF957558),
    availableGreen: Color(0xFF88AA7C),
    pendingAmber: Color(0xFFB6975C),
    charcoalGrey: Color(0xFFF4EEE4),
    slateGrey: Color(0xFFDBD0C0),
    graphite: Color(0xFF212121),
    darkSlate: Color(0xFF424242),
    mediumSlate: Color(0xFF757575),
    lightSlate: Color(0xFFBDBDBD),
    skyBlue: Color(0xFF7A5230),
    diamondDust: Color(0xFF5C3C22),
    iceBlue: Color(0xFF4C341F),
    steelBlue: Color(0xFF4E4338),
    pureWhite: Color(0xFF2E2419),
    pearlWhite: Color(0xFF362C21),
    mistWhite: Color(0xFF3E342A),
    opaqueWhite: Color(0xE62E2419),
    translucentWhite: Color(0x262E2419),
    correct: Color(0xFF36682C),
    wrong: Color(0xFFA33328),
    adminCyan: Color(0xFF1C7A7E),
    adminBlue: Color(0xFF33609F),
    adminIndigo: Color(0xFF5B4E9E),
    adminGreen: Color(0xFF3F7A34),
    adminAmber: Color(0xFF946610),
    adminMagenta: Color(0xFF9E4470),
    adminCoral: Color(0xFFB5392C),
    surface: Color(0xFFFFFFFF),
    surfaceStrong: Color(0xFFFFFDF9),
    surfaceSoft: Color(0xFFF9F5EE),
    textPrimary: Color(0xFF2E2419),
    textSecondary: Color(0xB32E2419),
    textMuted: Color(0x732E2419),
    divider: Color(0x142E2419),
    surfaceBorder: Color(0x1F2E2419),
  );

  /// Laguna (chiaro): Sabbia, acqua turchese, ibisco.
  static const AppPalette laguna = AppPalette(
    brandNightBlue: Color(0xFFDDEFEA),
    secondaryNightBlue: Color(0xFFE7F4F0),
    deepOcean: Color(0xFFB4D7D3),
    darkElegance: Color(0xFFF7F2E6),
    eleganceSoftNight: Color(0xFFFAF6EB),
    eleganceMidnight: Color(0xFFFFFCF5),
    eleganceDeepNavy: Color(0xFFFFFFFF),
    eleganceShadow: Color(0xFFE8DAB8),
    eleganceObsidian: Color(0xFFF9F6EE),
    slateMidnight: Color(0xFFC8E3DF),
    royalIndigo: Color(0xFFBCDCD8),
    electricBlue: Color(0xFFAFD5D1),
    vividSapphire: Color(0xFFA3CDCA),
    lavenderBlue: Color(0xFF7264B6),
    materialBlue: Color(0xFFC0DEDA),
    materialNavy: Color(0xFFCCE5E1),
    materialSteel: Color(0xFFABD2CF),
    materialSky: Color(0xFF419290),
    socialBlue: Color(0xFFB8D9D5),
    socialIndigo: Color(0xFFB6BED8),
    socialCobalt: Color(0xFF9FCBC8),
    socialSky: Color(0xFF258383),
    studentBlue: Color(0xFF80B9B7),
    studentSteel: Color(0xFF65A9A8),
    teacherIndigo: Color(0xFFA2A5CF),
    teacherNavy: Color(0xFFC0CBDD),
    availableBlue: Color(0xFF419290),
    availableGreen: Color(0xFF87AC7A),
    pendingAmber: Color(0xFFBB965A),
    charcoalGrey: Color(0xFFEEF6F0),
    slateGrey: Color(0xFFCEE0DB),
    graphite: Color(0xFF212121),
    darkSlate: Color(0xFF424242),
    mediumSlate: Color(0xFF757575),
    lightSlate: Color(0xFFBDBDBD),
    skyBlue: Color(0xFF0E7778),
    diamondDust: Color(0xFF0A5A5B),
    iceBlue: Color(0xFF114B4B),
    steelBlue: Color(0xFF2A4748),
    pureWhite: Color(0xFF1F2E2E),
    pearlWhite: Color(0xFF283635),
    mistWhite: Color(0xFF303E3D),
    opaqueWhite: Color(0xE61F2E2E),
    translucentWhite: Color(0x261F2E2E),
    correct: Color(0xFF336A2A),
    wrong: Color(0xFFAE3428),
    adminCyan: Color(0xFF1C6FA0),
    adminBlue: Color(0xFF3558B0),
    adminIndigo: Color(0xFF5A4BAE),
    adminGreen: Color(0xFF3C7D32),
    adminAmber: Color(0xFF9A640E),
    adminMagenta: Color(0xFFB0407A),
    adminCoral: Color(0xFFC13A2C),
    surface: Color(0xFFFFFFFF),
    surfaceStrong: Color(0xFFFFFCF5),
    surfaceSoft: Color(0xFFFAF6EB),
    textPrimary: Color(0xFF1F2E2E),
    textSecondary: Color(0xB31F2E2E),
    textMuted: Color(0x731F2E2E),
    divider: Color(0x141F2E2E),
    surfaceBorder: Color(0x1F1F2E2E),
  );

  /// Focus (scuro): Grafite e blu acciaio: niente distrazioni, solo studio.
  static const AppPalette focus = AppPalette(
    brandNightBlue: Color(0xFF242A33),
    secondaryNightBlue: Color(0xFF21272F),
    deepOcean: Color(0xFF323B47),
    darkElegance: Color(0xFF101216),
    eleganceSoftNight: Color(0xFF121418),
    eleganceMidnight: Color(0xFF15181D),
    eleganceDeepNavy: Color(0xFF1B1F25),
    eleganceShadow: Color(0xFF07080A),
    eleganceObsidian: Color(0xFF0C0D10),
    slateMidnight: Color(0xFF303843),
    royalIndigo: Color(0xFF37404D),
    electricBlue: Color(0xFF3E4857),
    vividSapphire: Color(0xFF455161),
    lavenderBlue: Color(0xFF908BBB),
    materialBlue: Color(0xFF353D4A),
    materialNavy: Color(0xFF2E3540),
    materialSteel: Color(0xFF414B5A),
    materialSky: Color(0xFF7C90AC),
    socialBlue: Color(0xFF394350),
    socialIndigo: Color(0xFF4B4D64),
    socialCobalt: Color(0xFF485364),
    socialSky: Color(0xFF8DA4C3),
    studentBlue: Color(0xFF5A687C),
    studentSteel: Color(0xFF697A92),
    teacherIndigo: Color(0xFF5E5F7D),
    teacherNavy: Color(0xFF414457),
    availableBlue: Color(0xFF7C90AC),
    availableGreen: Color(0xFF647D65),
    pendingAmber: Color(0xFF937E4D),
    charcoalGrey: Color(0xFF1C2128),
    slateGrey: Color(0xFF363B43),
    graphite: Color(0xFF212121),
    darkSlate: Color(0xFF424242),
    mediumSlate: Color(0xFF757575),
    lightSlate: Color(0xFFBDBDBD),
    skyBlue: Color(0xFF9BB4D6),
    diamondDust: Color(0xFFD9E4F2),
    iceBlue: Color(0xFFE6EDF7),
    steelBlue: Color(0xFFC9D0D9),
    pureWhite: Color(0xFFFFFFFF),
    pearlWhite: Color(0xFFF5F6F6),
    mistWhite: Color(0xFFECECEC),
    opaqueWhite: Color(0xE6FFFFFF),
    translucentWhite: Color(0x26FFFFFF),
    correct: Color(0xFF566C55),
    wrong: Color(0xFF623731),
    adminCyan: Color(0xFF7FBFC4),
    adminBlue: Color(0xFF8FA7D9),
    adminIndigo: Color(0xFFA6A0D8),
    adminGreen: Color(0xFF9CC49A),
    adminAmber: Color(0xFFD9B86A),
    adminMagenta: Color(0xFFC593B6),
    adminCoral: Color(0xFFD97A6C),
    surface: Color(0xFF1B1F25),
    surfaceStrong: Color(0xFF15181D),
    surfaceSoft: Color(0xFF121418),
    textPrimary: Color(0xFFFFFFFF),
    textSecondary: Color(0xB3FFFFFF),
    textMuted: Color(0x73FFFFFF),
    divider: Color(0x14FFFFFF),
    surfaceBorder: Color(0x1FFFFFFF),
  );

  /// Argilla (scuro): Carbone caldo e argilla, colori morbidi e sobri.
  static const AppPalette argilla = AppPalette(
    brandNightBlue: Color(0xFF3A3632),
    secondaryNightBlue: Color(0xFF363330),
    deepOcean: Color(0xFF4D3E36),
    darkElegance: Color(0xFF1F1E1D),
    eleganceSoftNight: Color(0xFF21211F),
    eleganceMidnight: Color(0xFF262624),
    eleganceDeepNavy: Color(0xFF2D2C2A),
    eleganceShadow: Color(0xFF141413),
    eleganceObsidian: Color(0xFF1A1918),
    slateMidnight: Color(0xFF4A3C36),
    royalIndigo: Color(0xFF534038),
    electricBlue: Color(0xFF5D443A),
    vividSapphire: Color(0xFF67483C),
    lavenderBlue: Color(0xFF9388B5),
    materialBlue: Color(0xFF503F37),
    materialNavy: Color(0xFF473B35),
    materialSteel: Color(0xFF60463B),
    materialSky: Color(0xFFB0634A),
    socialBlue: Color(0xFF574239),
    socialIndigo: Color(0xFF5B5461),
    socialCobalt: Color(0xFF6A4A3D),
    socialSky: Color(0xFFC66E51),
    studentBlue: Color(0xFF825343),
    studentSteel: Color(0xFF965C47),
    teacherIndigo: Color(0xFF6C6379),
    teacherNavy: Color(0xFF524C55),
    availableBlue: Color(0xFFB0634A),
    availableGreen: Color(0xFF6B7C5B),
    pendingAmber: Color(0xFF9A804A),
    charcoalGrey: Color(0xFF302E2B),
    slateGrey: Color(0xFF494642),
    graphite: Color(0xFF212121),
    darkSlate: Color(0xFF424242),
    mediumSlate: Color(0xFF757575),
    lightSlate: Color(0xFFBDBDBD),
    skyBlue: Color(0xFFD97757),
    diamondDust: Color(0xFFF4D5C6),
    iceBlue: Color(0xFFF6E2D6),
    steelBlue: Color(0xFFCBB1A8),
    pureWhite: Color(0xFFFAF9F5),
    pearlWhite: Color(0xFFF1F0EC),
    mistWhite: Color(0xFFE8E7E4),
    opaqueWhite: Color(0xE6FAF9F5),
    translucentWhite: Color(0x26FAF9F5),
    correct: Color(0xFF566749),
    wrong: Color(0xFF652F24),
    adminCyan: Color(0xFF7FB6B0),
    adminBlue: Color(0xFF8EA6CC),
    adminIndigo: Color(0xFFA89BD0),
    adminGreen: Color(0xFF9DBB85),
    adminAmber: Color(0xFFDDB463),
    adminMagenta: Color(0xFFC98FA8),
    adminCoral: Color(0xFFE0694F),
    surface: Color(0xFF2D2C2A),
    surfaceStrong: Color(0xFF262624),
    surfaceSoft: Color(0xFF21211F),
    textPrimary: Color(0xFFFAF9F5),
    textSecondary: Color(0xB3FAF9F5),
    textMuted: Color(0x73FAF9F5),
    divider: Color(0x14FAF9F5),
    surfaceBorder: Color(0x1FFAF9F5),
  );

  @override
  AppPalette copyWith({
    Color? brandNightBlue,
    Color? secondaryNightBlue,
    Color? deepOcean,
    Color? darkElegance,
    Color? eleganceSoftNight,
    Color? eleganceMidnight,
    Color? eleganceDeepNavy,
    Color? eleganceShadow,
    Color? eleganceObsidian,
    Color? slateMidnight,
    Color? royalIndigo,
    Color? electricBlue,
    Color? vividSapphire,
    Color? lavenderBlue,
    Color? materialBlue,
    Color? materialNavy,
    Color? materialSteel,
    Color? materialSky,
    Color? socialBlue,
    Color? socialIndigo,
    Color? socialCobalt,
    Color? socialSky,
    Color? studentBlue,
    Color? studentSteel,
    Color? teacherIndigo,
    Color? teacherNavy,
    Color? availableBlue,
    Color? availableGreen,
    Color? pendingAmber,
    Color? charcoalGrey,
    Color? slateGrey,
    Color? graphite,
    Color? darkSlate,
    Color? mediumSlate,
    Color? lightSlate,
    Color? skyBlue,
    Color? diamondDust,
    Color? iceBlue,
    Color? steelBlue,
    Color? pureWhite,
    Color? pearlWhite,
    Color? mistWhite,
    Color? opaqueWhite,
    Color? translucentWhite,
    Color? correct,
    Color? wrong,
    Color? adminCyan,
    Color? adminBlue,
    Color? adminIndigo,
    Color? adminGreen,
    Color? adminAmber,
    Color? adminMagenta,
    Color? adminCoral,
    Color? surface,
    Color? surfaceStrong,
    Color? surfaceSoft,
    Color? textPrimary,
    Color? textSecondary,
    Color? textMuted,
    Color? divider,
    Color? surfaceBorder,
  }) {
    return AppPalette(
      brandNightBlue: brandNightBlue ?? this.brandNightBlue,
      secondaryNightBlue: secondaryNightBlue ?? this.secondaryNightBlue,
      deepOcean: deepOcean ?? this.deepOcean,
      darkElegance: darkElegance ?? this.darkElegance,
      eleganceSoftNight: eleganceSoftNight ?? this.eleganceSoftNight,
      eleganceMidnight: eleganceMidnight ?? this.eleganceMidnight,
      eleganceDeepNavy: eleganceDeepNavy ?? this.eleganceDeepNavy,
      eleganceShadow: eleganceShadow ?? this.eleganceShadow,
      eleganceObsidian: eleganceObsidian ?? this.eleganceObsidian,
      slateMidnight: slateMidnight ?? this.slateMidnight,
      royalIndigo: royalIndigo ?? this.royalIndigo,
      electricBlue: electricBlue ?? this.electricBlue,
      vividSapphire: vividSapphire ?? this.vividSapphire,
      lavenderBlue: lavenderBlue ?? this.lavenderBlue,
      materialBlue: materialBlue ?? this.materialBlue,
      materialNavy: materialNavy ?? this.materialNavy,
      materialSteel: materialSteel ?? this.materialSteel,
      materialSky: materialSky ?? this.materialSky,
      socialBlue: socialBlue ?? this.socialBlue,
      socialIndigo: socialIndigo ?? this.socialIndigo,
      socialCobalt: socialCobalt ?? this.socialCobalt,
      socialSky: socialSky ?? this.socialSky,
      studentBlue: studentBlue ?? this.studentBlue,
      studentSteel: studentSteel ?? this.studentSteel,
      teacherIndigo: teacherIndigo ?? this.teacherIndigo,
      teacherNavy: teacherNavy ?? this.teacherNavy,
      availableBlue: availableBlue ?? this.availableBlue,
      availableGreen: availableGreen ?? this.availableGreen,
      pendingAmber: pendingAmber ?? this.pendingAmber,
      charcoalGrey: charcoalGrey ?? this.charcoalGrey,
      slateGrey: slateGrey ?? this.slateGrey,
      graphite: graphite ?? this.graphite,
      darkSlate: darkSlate ?? this.darkSlate,
      mediumSlate: mediumSlate ?? this.mediumSlate,
      lightSlate: lightSlate ?? this.lightSlate,
      skyBlue: skyBlue ?? this.skyBlue,
      diamondDust: diamondDust ?? this.diamondDust,
      iceBlue: iceBlue ?? this.iceBlue,
      steelBlue: steelBlue ?? this.steelBlue,
      pureWhite: pureWhite ?? this.pureWhite,
      pearlWhite: pearlWhite ?? this.pearlWhite,
      mistWhite: mistWhite ?? this.mistWhite,
      opaqueWhite: opaqueWhite ?? this.opaqueWhite,
      translucentWhite: translucentWhite ?? this.translucentWhite,
      correct: correct ?? this.correct,
      wrong: wrong ?? this.wrong,
      adminCyan: adminCyan ?? this.adminCyan,
      adminBlue: adminBlue ?? this.adminBlue,
      adminIndigo: adminIndigo ?? this.adminIndigo,
      adminGreen: adminGreen ?? this.adminGreen,
      adminAmber: adminAmber ?? this.adminAmber,
      adminMagenta: adminMagenta ?? this.adminMagenta,
      adminCoral: adminCoral ?? this.adminCoral,
      surface: surface ?? this.surface,
      surfaceStrong: surfaceStrong ?? this.surfaceStrong,
      surfaceSoft: surfaceSoft ?? this.surfaceSoft,
      textPrimary: textPrimary ?? this.textPrimary,
      textSecondary: textSecondary ?? this.textSecondary,
      textMuted: textMuted ?? this.textMuted,
      divider: divider ?? this.divider,
      surfaceBorder: surfaceBorder ?? this.surfaceBorder,
    );
  }

  @override
  AppPalette lerp(ThemeExtension<AppPalette>? other, double t) {
    if (other is! AppPalette) return this;
    return AppPalette(
      brandNightBlue: Color.lerp(brandNightBlue, other.brandNightBlue, t)!,
      secondaryNightBlue: Color.lerp(secondaryNightBlue, other.secondaryNightBlue, t)!,
      deepOcean: Color.lerp(deepOcean, other.deepOcean, t)!,
      darkElegance: Color.lerp(darkElegance, other.darkElegance, t)!,
      eleganceSoftNight: Color.lerp(eleganceSoftNight, other.eleganceSoftNight, t)!,
      eleganceMidnight: Color.lerp(eleganceMidnight, other.eleganceMidnight, t)!,
      eleganceDeepNavy: Color.lerp(eleganceDeepNavy, other.eleganceDeepNavy, t)!,
      eleganceShadow: Color.lerp(eleganceShadow, other.eleganceShadow, t)!,
      eleganceObsidian: Color.lerp(eleganceObsidian, other.eleganceObsidian, t)!,
      slateMidnight: Color.lerp(slateMidnight, other.slateMidnight, t)!,
      royalIndigo: Color.lerp(royalIndigo, other.royalIndigo, t)!,
      electricBlue: Color.lerp(electricBlue, other.electricBlue, t)!,
      vividSapphire: Color.lerp(vividSapphire, other.vividSapphire, t)!,
      lavenderBlue: Color.lerp(lavenderBlue, other.lavenderBlue, t)!,
      materialBlue: Color.lerp(materialBlue, other.materialBlue, t)!,
      materialNavy: Color.lerp(materialNavy, other.materialNavy, t)!,
      materialSteel: Color.lerp(materialSteel, other.materialSteel, t)!,
      materialSky: Color.lerp(materialSky, other.materialSky, t)!,
      socialBlue: Color.lerp(socialBlue, other.socialBlue, t)!,
      socialIndigo: Color.lerp(socialIndigo, other.socialIndigo, t)!,
      socialCobalt: Color.lerp(socialCobalt, other.socialCobalt, t)!,
      socialSky: Color.lerp(socialSky, other.socialSky, t)!,
      studentBlue: Color.lerp(studentBlue, other.studentBlue, t)!,
      studentSteel: Color.lerp(studentSteel, other.studentSteel, t)!,
      teacherIndigo: Color.lerp(teacherIndigo, other.teacherIndigo, t)!,
      teacherNavy: Color.lerp(teacherNavy, other.teacherNavy, t)!,
      availableBlue: Color.lerp(availableBlue, other.availableBlue, t)!,
      availableGreen: Color.lerp(availableGreen, other.availableGreen, t)!,
      pendingAmber: Color.lerp(pendingAmber, other.pendingAmber, t)!,
      charcoalGrey: Color.lerp(charcoalGrey, other.charcoalGrey, t)!,
      slateGrey: Color.lerp(slateGrey, other.slateGrey, t)!,
      graphite: Color.lerp(graphite, other.graphite, t)!,
      darkSlate: Color.lerp(darkSlate, other.darkSlate, t)!,
      mediumSlate: Color.lerp(mediumSlate, other.mediumSlate, t)!,
      lightSlate: Color.lerp(lightSlate, other.lightSlate, t)!,
      skyBlue: Color.lerp(skyBlue, other.skyBlue, t)!,
      diamondDust: Color.lerp(diamondDust, other.diamondDust, t)!,
      iceBlue: Color.lerp(iceBlue, other.iceBlue, t)!,
      steelBlue: Color.lerp(steelBlue, other.steelBlue, t)!,
      pureWhite: Color.lerp(pureWhite, other.pureWhite, t)!,
      pearlWhite: Color.lerp(pearlWhite, other.pearlWhite, t)!,
      mistWhite: Color.lerp(mistWhite, other.mistWhite, t)!,
      opaqueWhite: Color.lerp(opaqueWhite, other.opaqueWhite, t)!,
      translucentWhite: Color.lerp(translucentWhite, other.translucentWhite, t)!,
      correct: Color.lerp(correct, other.correct, t)!,
      wrong: Color.lerp(wrong, other.wrong, t)!,
      adminCyan: Color.lerp(adminCyan, other.adminCyan, t)!,
      adminBlue: Color.lerp(adminBlue, other.adminBlue, t)!,
      adminIndigo: Color.lerp(adminIndigo, other.adminIndigo, t)!,
      adminGreen: Color.lerp(adminGreen, other.adminGreen, t)!,
      adminAmber: Color.lerp(adminAmber, other.adminAmber, t)!,
      adminMagenta: Color.lerp(adminMagenta, other.adminMagenta, t)!,
      adminCoral: Color.lerp(adminCoral, other.adminCoral, t)!,
      surface: Color.lerp(surface, other.surface, t)!,
      surfaceStrong: Color.lerp(surfaceStrong, other.surfaceStrong, t)!,
      surfaceSoft: Color.lerp(surfaceSoft, other.surfaceSoft, t)!,
      textPrimary: Color.lerp(textPrimary, other.textPrimary, t)!,
      textSecondary: Color.lerp(textSecondary, other.textSecondary, t)!,
      textMuted: Color.lerp(textMuted, other.textMuted, t)!,
      divider: Color.lerp(divider, other.divider, t)!,
      surfaceBorder: Color.lerp(surfaceBorder, other.surfaceBorder, t)!,
    );
  }
}

extension AppPaletteContext on BuildContext {
  /// Palette del tema corrente; se il tema non la registra usa [AppPalette.kiwi].
  AppPalette get palette =>
      Theme.of(this).extension<AppPalette>() ?? AppPalette.kiwi;
}

/// Temi disponibili. L'`id` viene salvato sul dispositivo: non rinominarlo.
enum StudentLabTheme {
  notte('notte', 'Notte', 'Blu notte, il tema di sempre', false),
  ardesia('ardesia', 'Ardesia', 'Grafite con verde acqua', false),
  terra('terra', 'Terra', 'Marrone caldo, riposante', false),
  bosco('bosco', 'Bosco', 'Verde di foglie e muschio', false),
  pietra('pietra', 'Pietra', 'Travertino e ardesia', false),
  fico('fico', 'Fico', 'Buccia viola, polpa rosa, foglia verde', false),
  torbiera('torbiera', 'Torbiera', 'Torba, muschio, laghi ed erica d’Irlanda', false),
  focus('focus', 'Focus', 'Grafite e blu acciaio: niente distrazioni', false),
  argilla('argilla', 'Argilla', 'Carbone caldo e argilla, sobrio e morbido', false),
  kiwi('kiwi', 'Kiwi', 'Polpa verde, cuore crema, semi scuri', true),
  pesca('pesca', 'Pesca', 'Buccia rosata e polpa dorata', true),
  antartide('antartide', 'Antartide', 'Ghiaccio, neve e mare profondo', true),
  cocco('cocco', 'Cocco', 'Polpa bianca, guscio bruno, palma', true),
  laguna('laguna', 'Laguna', 'Sabbia, acqua turchese, ibisco', true);

  final String id;
  final String label;
  final String description;
  final bool isLight;

  const StudentLabTheme(this.id, this.label, this.description, this.isLight);

  AppPalette get palette => switch (this) {
        StudentLabTheme.notte => AppPalette.night,
        StudentLabTheme.ardesia => AppPalette.ardesia,
        StudentLabTheme.terra => AppPalette.terra,
        StudentLabTheme.bosco => AppPalette.bosco,
        StudentLabTheme.pietra => AppPalette.pietra,
        StudentLabTheme.fico => AppPalette.fico,
        StudentLabTheme.torbiera => AppPalette.torbiera,
        StudentLabTheme.focus => AppPalette.focus,
        StudentLabTheme.argilla => AppPalette.argilla,
        StudentLabTheme.kiwi => AppPalette.kiwi,
        StudentLabTheme.pesca => AppPalette.pesca,
        StudentLabTheme.antartide => AppPalette.antartide,
        StudentLabTheme.cocco => AppPalette.cocco,
        StudentLabTheme.laguna => AppPalette.laguna,
      };

  static StudentLabTheme fromId(String? id) =>
      StudentLabTheme.values.firstWhere((t) => t.id == id, orElse: () => StudentLabTheme.kiwi);
}
